/* C++ enum of unicode character names.
 *
 * Because of the limits of C++ identifiers the following characters have been remapped:
 *   " " -> "_"
 *   "-" -> "_"
 *   "'" -> ""
 *   """ -> ""
 *   "." -> ""
 *   "+" -> "_"
 *   "/" -> "_"
 *   "?" -> ""
 *   "!" -> ""
 *   "\" -> ""
 *   "," -> ""
 *   ":" -> ""
 *
 * Because the following names are not valid C++ identifiers they have been prepended with "_":
 *   "long" -> "_long"
 *   "short" -> "_short"
 *   "not" -> "_not"
 *   "break" -> "_break"
 *   "new" -> "_new"
 *   "double" -> "_double"
 *   "1_12_of_an_inch" -> "_1_12_of_an_inch"
 *   "1_lakh" -> "_1_lakh"
 *   "100_000" -> "_100_000"
 *   "2_lakh" -> "_2_lakh"
 *   "200_000" -> "_200_000"
 *   "1_crore" -> "_1_crore"
 *   "10_million" -> "_10_million"
 *   "100_lakh" -> "_100_lakh"
 *   "2_crore" -> "_2_crore"
 *   "20_million" -> "_20_million"
 *   "200_lakh" -> "_200_lakh"
 *
 * Because some names have multiple definitions their meaning had to be limited to their first one,
 * a list of these can be found at the bottom of the file.
 */

enum U
{
	NOTHING = 0x0,
	START_OF_HEADING = 0x1,
	START_OF_TEXT = 0x2,
	END_OF_TEXT = 0x3,
	END_OF_TRANSMISSION = 0x4,
	ENQUIRY = 0x5,
	ACKNOWLEDGE = 0x6,
	BELL = 0x7,
	BACKSPACE = 0x8,
	CHARACTER_TABULATION = 0x9,
	horizontal_tabulation = 0x9,
	HT = 0x9,
	tab = 0x9,
	LINE_FEED = 0xA,
	LF = 0xA,
	new_line = 0xA,
	NL = 0xA,
	end_of_line = 0xA,
	EOL = 0xA,
	LINE_TABULATION = 0xB,
	vertical_tabulation = 0xB,
	VT = 0xB,
	FORM_FEED = 0xC,
	FF = 0xC,
	CARRIAGE_RETURN = 0xD,
	CR = 0xD,
	SHIFT_OUT = 0xE,
	LOCKING_SHIFT_ONE = 0xE,
	SHIFT_IN = 0xF,
	LOCKING_SHIFT_ZERO = 0xF,
	DATA_LINK_ESCAPE = 0x10,
	DEVICE_CONTROL_ONE = 0x11,
	DEVICE_CONTROL_TWO = 0x12,
	DEVICE_CONTROL_THREE = 0x13,
	DEVICE_CONTROL_FOUR = 0x14,
	NEGATIVE_ACKNOWLEDGE = 0x15,
	SYNCHRONOUS_IDLE = 0x16,
	END_OF_TRANSMISSION_BLOCK = 0x17,
	CANCEL = 0x18,
	END_OF_MEDIUM = 0x19,
	SUBSTITUTE = 0x1A,
	ESCAPE = 0x1B,
	INFORMATION_SEPARATOR_FOUR = 0x1C,
	file_separator = 0x1C,
	FS = 0x1C,
	INFORMATION_SEPARATOR_THREE = 0x1D,
	group_separator = 0x1D,
	GS = 0x1D,
	INFORMATION_SEPARATOR_TWO = 0x1E,
	record_separator = 0x1E,
	RS = 0x1E,
	INFORMATION_SEPARATOR_ONE = 0x1F,
	unit_separator = 0x1F,
	US = 0x1F,
	SPACE = 0x20,
	EXCLAMATION_MARK = 0x21,
	factorial = 0x21,
	bang = 0x21,
	QUOTATION_MARK = 0x22,
	NUMBER_SIGN = 0x23,
	pound_sign = 0x23,
	hash = 0x23,
	crosshatch = 0x23,
	octothorpe = 0x23,
	DOLLAR_SIGN = 0x24,
	escudo = 0x24,
	PERCENT_SIGN = 0x25,
	AMPERSAND = 0x26,
	APOSTROPHE = 0x27,
	apostrophe_quote = 0x27,
	APL_quote = 0x27,
	LEFT_PARENTHESIS = 0x28,
	opening_parenthesis = 0x28,
	RIGHT_PARENTHESIS = 0x29,
	closing_parenthesis = 0x29,
	ASTERISK = 0x2A,
	star = 0x2A,
	PLUS_SIGN = 0x2B,
	COMMA = 0x2C,
	decimal_separator = 0x2C,
	HYPHEN_MINUS = 0x2D,
	hyphen_or_minus_sign = 0x2D,
	period = 0x2E,
	dot = 0x2E,
	decimal_point = 0x2E,
	SOLIDUS = 0x2F,
	slash = 0x2F,
	virgule = 0x2F,
	DIGIT_ZERO = 0x30,
	DIGIT_ONE = 0x31,
	DIGIT_TWO = 0x32,
	DIGIT_THREE = 0x33,
	DIGIT_FOUR = 0x34,
	DIGIT_FIVE = 0x35,
	DIGIT_SIX = 0x36,
	DIGIT_SEVEN = 0x37,
	DIGIT_EIGHT = 0x38,
	DIGIT_NINE = 0x39,
	COLON = 0x3A,
	SEMICOLON = 0x3B,
	LESS_THAN_SIGN = 0x3C,
	EQUALS_SIGN = 0x3D,
	GREATER_THAN_SIGN = 0x3E,
	QUESTION_MARK = 0x3F,
	COMMERCIAL_AT = 0x40,
	at_sign = 0x40,
	LATIN_CAPITAL_LETTER_A = 0x41,
	LATIN_CAPITAL_LETTER_B = 0x42,
	LATIN_CAPITAL_LETTER_C = 0x43,
	LATIN_CAPITAL_LETTER_D = 0x44,
	LATIN_CAPITAL_LETTER_E = 0x45,
	LATIN_CAPITAL_LETTER_F = 0x46,
	LATIN_CAPITAL_LETTER_G = 0x47,
	LATIN_CAPITAL_LETTER_H = 0x48,
	LATIN_CAPITAL_LETTER_I = 0x49,
	LATIN_CAPITAL_LETTER_J = 0x4A,
	LATIN_CAPITAL_LETTER_K = 0x4B,
	LATIN_CAPITAL_LETTER_L = 0x4C,
	LATIN_CAPITAL_LETTER_M = 0x4D,
	LATIN_CAPITAL_LETTER_N = 0x4E,
	LATIN_CAPITAL_LETTER_O = 0x4F,
	LATIN_CAPITAL_LETTER_P = 0x50,
	LATIN_CAPITAL_LETTER_Q = 0x51,
	LATIN_CAPITAL_LETTER_R = 0x52,
	LATIN_CAPITAL_LETTER_S = 0x53,
	LATIN_CAPITAL_LETTER_T = 0x54,
	LATIN_CAPITAL_LETTER_U = 0x55,
	LATIN_CAPITAL_LETTER_V = 0x56,
	LATIN_CAPITAL_LETTER_W = 0x57,
	LATIN_CAPITAL_LETTER_X = 0x58,
	LATIN_CAPITAL_LETTER_Y = 0x59,
	LATIN_CAPITAL_LETTER_Z = 0x5A,
	LEFT_SQUARE_BRACKET = 0x5B,
	opening_square_bracket = 0x5B,
	REVERSE_SOLIDUS = 0x5C,
	backslash = 0x5C,
	RIGHT_SQUARE_BRACKET = 0x5D,
	closing_square_bracket = 0x5D,
	CIRCUMFLEX_ACCENT = 0x5E,
	LOW_LINE = 0x5F,
	spacing_underscore = 0x5F,
	GRAVE_ACCENT = 0x60,
	LATIN_SMALL_LETTER_A = 0x61,
	LATIN_SMALL_LETTER_B = 0x62,
	LATIN_SMALL_LETTER_C = 0x63,
	LATIN_SMALL_LETTER_D = 0x64,
	LATIN_SMALL_LETTER_E = 0x65,
	LATIN_SMALL_LETTER_F = 0x66,
	LATIN_SMALL_LETTER_G = 0x67,
	LATIN_SMALL_LETTER_H = 0x68,
	LATIN_SMALL_LETTER_I = 0x69,
	LATIN_SMALL_LETTER_J = 0x6A,
	LATIN_SMALL_LETTER_K = 0x6B,
	LATIN_SMALL_LETTER_L = 0x6C,
	LATIN_SMALL_LETTER_M = 0x6D,
	LATIN_SMALL_LETTER_N = 0x6E,
	LATIN_SMALL_LETTER_O = 0x6F,
	LATIN_SMALL_LETTER_P = 0x70,
	LATIN_SMALL_LETTER_Q = 0x71,
	LATIN_SMALL_LETTER_R = 0x72,
	LATIN_SMALL_LETTER_S = 0x73,
	LATIN_SMALL_LETTER_T = 0x74,
	LATIN_SMALL_LETTER_U = 0x75,
	LATIN_SMALL_LETTER_V = 0x76,
	LATIN_SMALL_LETTER_W = 0x77,
	LATIN_SMALL_LETTER_X = 0x78,
	LATIN_SMALL_LETTER_Y = 0x79,
	LATIN_SMALL_LETTER_Z = 0x7A,
	LEFT_CURLY_BRACKET = 0x7B,
	opening_curly_bracket = 0x7B,
	left_brace = 0x7B,
	VERTICAL_LINE = 0x7C,
	vertical_bar = 0x7C,
	RIGHT_CURLY_BRACKET = 0x7D,
	closing_curly_bracket = 0x7D,
	right_brace = 0x7D,
	TILDE = 0x7E
};